---
language: go
go:
- '1.3'
sudo: false
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/.local/bin:$PATH
  - DATABASE_URL=postgres://postgres@localhost:5432/travis
  - PYTEST_FLAGS="--cov-report term-missing --cov tory_sync_from_joyent --cov tory_register --pep8 -rs"
  - secure: QwUX7PAXs8Xe+1r4dHOatDULewQty9dMufBZOTftg5eeeZFm+oFoir8nSnxkijIb/M3I0UUb94rnAQ+rBpk+Z4aGARzQBTHFayXUUhFI2x0BkOOuNgXeoJC1gOx/M29SMgHjbB2t5G/z9WZ+dCZokmF+TAsUVfBxkOw93hcr/9c=
addons:
  postgresql: '9.3'
  artifacts:
    key:
      secure: ce0uEeu7AG2I6CQkreCXjeDzL451IBvnuVyEiOX5811ZZ85KlniOP9X06dQek3jrAkyS5z383Vs10bz8Wzam3WxVC565vs0Wuiuu/NE+KUecdnffD77ekrJr9T8lyGJIGJeSoGCbD31MWQfEzZoMna2/lJ8dq1b+cCD+nqRso9s=
    secret:
      secure: Ub6hECj5J9aUv/6nnSutkrz32TnAvFe9DuDX0sitOPrmfEf9A3mF/3xent2PwnkRapUfTtu2QF+/EnI+cr33aO0UQ+hOMV/mHFEOBsJZzLMrmr1X9LB6ful0uk/yQX1Ki71XN6YosC7okqcf+LJjRjAe3Mv/EoO3BH4kDtWwUvg=
    bucket: modcloth-public-travis-artifacts
    permissions: public-read
    paths:
    - $(ls -1 tory-*-amd64.tar.bz2 | tr "\n" ":")
    - $(ls -1 ./*.coverprofile | tr "\n" ":")
    - SHA256SUMS
    - coverage.html
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- mkdir -p $HOME/.local/bin
- pip install --user -r requirements.txt
before_script:
- createdb -U postgres travis
after_success:
- CGO_ENABLED=0 go install -a std
- go get github.com/mitchellh/gox
- make crosstars
- bin/enqueue-build
notifications:
  email: github+tory@modcloth.com
deploy:
  provider: pypi
  user: modcloth
  password:
    secure: NIXyfZtdEcW/+GpsIk2KsItrX/tqASFqQL1yoR7Pq+h/ybnKIYy8rSTj161CpobdU8xUqn7DUS2AY5G2Owc3SCyYXQAEHpWHTCj3s/GJXGwXbhrk5Fl6ZKNIkP0XnfU7xHzO0gm0K7Lw7GSGvSGZTZMd+jPwlGYBOGn/Dwq55iM=
  on:
    tags: true
    repo: modcloth/tory
